"""The check-commit-metadata action, run as CI runs it: against real git repositories."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

ACTION = Path(__file__).parents[2] / ".github" / "actions" / "check-commit-metadata"
SCRIPT = ACTION / "check_authorship.py"
NAME = "Jane Doe"
EMAIL = "jane@example.com"
NOREPLY = "1+jane@users.noreply.github.com"
DOMAIN = "blocked.example"
GITHUB = ("GitHub", "noreply@github.com")
DEPENDABOT = ("dependabot[bot]", "49699333+dependabot[bot]@users.noreply.github.com")
RENOVATE = ("renovate[bot]", "29139614+renovate[bot]@users.noreply.github.com")
# Git knows the empty tree without it being stored.
EMPTY_TREE = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"


def isolated_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    # Away from the machine's git config, so no signing or hook runs on the commits under test,
    # and away from a CI run's variables, so the output is the same everywhere.
    env = {k: v for k, v in os.environ.items() if not k.startswith(("GITHUB_", "GIT_"))}
    return {**env, "GIT_CONFIG_GLOBAL": os.devnull, "GIT_CONFIG_NOSYSTEM": "1", **(extra or {})}


def git(repo: Path, *args: str, stdin: str | None = None, env: dict[str, str] | None = None) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        input=stdin,
        check=True,
        capture_output=True,
        text=True,
        env=isolated_env(env),
    ).stdout.strip()


def commit(
    repo: Path,
    message: str,
    *,
    author: tuple[str, str] = (NAME, EMAIL),
    committer: tuple[str, str] | None = None,
    parents: tuple[str, ...] | None = None,
) -> str:
    """Records an empty commit on the current branch with exactly this message and identity.

    Built with `git commit-tree`, the plumbing command, so the message reaches the repository
    byte for byte, as a push would deliver it.
    """
    committer = committer or author
    identity = {
        "GIT_AUTHOR_NAME": author[0],
        "GIT_AUTHOR_EMAIL": author[1],
        "GIT_COMMITTER_NAME": committer[0],
        "GIT_COMMITTER_EMAIL": committer[1],
    }
    if parents is None:
        has_head = subprocess.run(["git", "-C", str(repo), "rev-parse", "--verify", "-q", "HEAD"], check=False)
        parents = ("HEAD",) if has_head.returncode == 0 else ()
    flags = [flag for parent in parents for flag in ("-p", parent)]
    sha = git(repo, "commit-tree", EMPTY_TREE, *flags, stdin=message, env=identity)
    git(repo, "update-ref", "HEAD", sha)
    return sha


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    path = tmp_path / "repo"
    path.mkdir()
    git(path, "init", "--quiet", "--initial-branch=main")
    commit(path, "Start")
    return path


@pytest.fixture
def branch(repo: Path) -> Path:
    git(repo, "switch", "--quiet", "--create", "feat/x")
    return repo


def check(repo: Path, *extra: str, base: str = "main", head: str = "HEAD") -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            *(sys.executable, str(SCRIPT), "--base", base, "--head", head),
            *("--name", NAME, "--email", EMAIL, "--email", NOREPLY),
            *("--blocked-domain", DOMAIN),
            *extra,
        ],
        cwd=repo,
        env=isolated_env(),
        capture_output=True,
        text=True,
        check=False,
    )


def test_clean_commits_pass(branch: Path) -> None:
    commit(branch, "Add a thing\n\nValues generated by the scheduler are kept.")
    commit(branch, "Link the docs at https://docs.example.org")
    result = check(branch)
    assert result.returncode == 0, result.stdout
    assert "2 commit(s) checked" in result.stdout


def test_commits_already_on_the_base_are_not_checked(repo: Path) -> None:
    commit(repo, "Old", author=("Someone Else", "else@example.com"))
    git(repo, "switch", "--quiet", "--create", "feat/x")
    commit(repo, "New")
    assert check(repo).returncode == 0


@pytest.mark.parametrize(
    ("name", "email"),
    [("Someone Else", EMAIL), (NAME, "other@example.com")],
)
def test_another_author_fails_and_names_the_commit(branch: Path, name: str, email: str) -> None:
    sha = commit(branch, "Sneak in", author=(name, email))[:12]
    result = check(branch)
    assert result.returncode == 1
    assert f'commit {sha} "Sneak in"' in result.stdout
    assert f"author is {name} <{email}>" in result.stdout
    assert "--reset-author" in result.stdout


def test_another_committer_fails(branch: Path) -> None:
    # What applying someone's patch leaves: the author kept, the committer changed.
    commit(branch, "Applied", committer=("Bot", "bot@example.com"))
    result = check(branch)
    assert result.returncode == 1
    assert "committer is Bot <bot@example.com>" in result.stdout
    assert "author is" not in result.stdout


def test_email_case_does_not_matter(branch: Path) -> None:
    commit(branch, "Shout", author=(NAME, EMAIL.upper()))
    assert check(branch).returncode == 0


def test_every_accepted_email_passes(branch: Path) -> None:
    commit(branch, "From the web editor", author=(NAME, NOREPLY), committer=GITHUB)
    commit(branch, "From my machine", author=(NAME, EMAIL))
    assert check(branch).returncode == 0


def test_github_as_committer_passes(branch: Path) -> None:
    # "Update branch": a merge of the base, authored by the maintainer, committed by GitHub.
    tip = commit(branch, "Work")
    git(branch, "switch", "--quiet", "main")
    base = commit(branch, "Meanwhile on main")
    git(branch, "switch", "--quiet", "feat/x")
    commit(branch, "Merge branch 'main' into feat/x", committer=GITHUB, parents=(tip, base))
    result = check(branch)
    assert result.returncode == 0, result.stdout
    assert "2 commit(s) checked" in result.stdout


def test_github_as_committer_does_not_vouch_for_another_author(branch: Path) -> None:
    commit(branch, "Suggested", author=("Someone Else", "else@example.com"), committer=GITHUB)
    result = check(branch)
    assert result.returncode == 1
    assert "author is Someone Else" in result.stdout
    assert "committer is" not in result.stdout


@pytest.mark.parametrize(
    "line",
    [
        "Co-Authored-By: Someone <someone@example.com>",
        "co-authored-by:Someone <someone@example.com>",
        "Generated with Some Tool",
        "🤖 Generated with [Some Tool](https://tool.example)",
        "_Generated by a tool_",
        "Requested by Jane · project thread",
        "_Requested by **Jane** · [project thread](https://x.example)_",
        f"See https://{DOMAIN}/session/1",
        f"See https://code.{DOMAIN}/x",
    ],
)
def test_forbidden_lines_in_a_message_fail(branch: Path, line: str) -> None:
    commit(branch, f"Do it\n\n{line}")
    result = check(branch)
    assert result.returncode == 1
    assert "message line 3" in result.stdout
    assert "git rebase -i main" in result.stdout


@pytest.mark.parametrize(
    "line",
    [
        "Values generated by the scheduler",
        "Requested by the product owner",
        "The thread requested by Jane",
        f"https://not{DOMAIN}/",
        f"https://{DOMAIN}x.org/",
    ],
)
def test_lookalike_lines_pass(branch: Path, line: str) -> None:
    commit(branch, f"Do it\n\n{line}")
    result = check(branch)
    assert result.returncode == 0, result.stdout


def test_every_blocked_domain_is_checked(branch: Path) -> None:
    commit(branch, "Do it\n\nhttps://second.example/x")
    assert check(branch).returncode == 0
    result = check(branch, "--blocked-domain", "second.example")
    assert result.returncode == 1
    assert "a link to second.example" in result.stdout


def test_every_problem_is_reported_at_once(branch: Path) -> None:
    commit(branch, "First", author=("A", "a@example.com"))
    commit(branch, "Second\n\nCo-Authored-By: B <b@example.com>")
    result = check(branch)
    assert result.returncode == 1
    assert '"First"' in result.stdout
    assert '"Second"' in result.stdout


def test_ci_gets_an_error_annotation(branch: Path) -> None:
    commit(branch, "First", author=("A", "a@example.com"))
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--base", "main", "--head", "HEAD"] + ["--name", NAME, "--email", EMAIL],
        cwd=branch,
        env=isolated_env({"GITHUB_ACTIONS": "true"}),
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 1
    assert "::error title=Check commit metadata::1 of 1 commit(s)" in result.stdout


# Dependabot


def dependabot_commit(repo: Path, message: str = "Bump a from 1 to 2") -> str:
    return commit(repo, message, author=DEPENDABOT, committer=GITHUB)


def test_dependabot_passes_in_its_own_pull_request(branch: Path) -> None:
    dependabot_commit(branch)
    # The maintainer may still push onto Dependabot's branch.
    commit(branch, "Adapt the code to a 2")
    result = check(branch, "--allow-dependabot", "--pr-author", "dependabot[bot]")
    assert result.returncode == 0, result.stdout


@pytest.mark.parametrize(
    "extra",
    [
        # Not allowed at all.
        ("--pr-author", "dependabot[bot]"),
        # Allowed, but someone else opened the pull request: the commit only claims to be the bot's.
        ("--allow-dependabot", "--pr-author", "someone"),
        ("--allow-dependabot",),
    ],
)
def test_dependabot_fails_otherwise(branch: Path, extra: tuple[str, ...]) -> None:
    dependabot_commit(branch)
    result = check(branch, *extra)
    assert result.returncode == 1
    assert "author is dependabot[bot]" in result.stdout


def test_dependabot_messages_are_still_checked(branch: Path) -> None:
    dependabot_commit(branch, f"Bump a\n\nSee https://{DOMAIN}/x")
    result = check(branch, "--allow-dependabot", "--pr-author", "dependabot[bot]")
    assert result.returncode == 1
    assert f"a link to {DOMAIN}" in result.stdout
    assert "author is" not in result.stdout


# Renovate


@pytest.mark.parametrize(
    "committer",
    [
        # Commits made through GitHub's API (Renovate's platformCommit), signed by GitHub.
        GITHUB,
        # Commits made with git and pushed.
        RENOVATE,
    ],
)
def test_renovate_passes_in_its_own_pull_request(branch: Path, committer: tuple[str, str]) -> None:
    commit(branch, "chore(deps): update caddy to v2.11", author=RENOVATE, committer=committer)
    commit(branch, "Adapt the Caddyfile")
    result = check(branch, "--allow-renovate", "--pr-author", "renovate[bot]")
    assert result.returncode == 0, result.stdout


@pytest.mark.parametrize(
    "extra",
    [
        ("--pr-author", "renovate[bot]"),
        ("--allow-renovate", "--pr-author", "someone"),
        ("--allow-renovate",),
        # Each bot only in its own pull requests.
        ("--allow-renovate", "--allow-dependabot", "--pr-author", "dependabot[bot]"),
    ],
)
def test_renovate_fails_otherwise(branch: Path, extra: tuple[str, ...]) -> None:
    commit(branch, "chore(deps): update caddy", author=RENOVATE, committer=GITHUB)
    result = check(branch, *extra)
    assert result.returncode == 1
    assert "author is renovate[bot]" in result.stdout


def test_dependabot_fails_in_renovate_pull_requests(branch: Path) -> None:
    dependabot_commit(branch)
    result = check(branch, "--allow-renovate", "--allow-dependabot", "--pr-author", "renovate[bot]")
    assert result.returncode == 1
    assert "author is dependabot[bot]" in result.stdout


def test_renovate_messages_are_still_checked(branch: Path) -> None:
    commit(branch, f"chore(deps): update caddy\n\nSee https://{DOMAIN}/x", author=RENOVATE, committer=GITHUB)
    result = check(branch, "--allow-renovate", "--pr-author", "renovate[bot]")
    assert result.returncode == 1
    assert f"a link to {DOMAIN}" in result.stdout
    assert "author is" not in result.stdout


# Fetching, as the action does: the commits are not in the caller's checkout.


@pytest.fixture
def remote(branch: Path) -> tuple[Path, str, str]:
    """A repository like GitHub's: the pull request's head is only under refs/pull/1/head."""
    base = git(branch, "rev-parse", "main")
    commit(branch, "First")
    head = commit(branch, "Second", author=("Someone Else", "else@example.com"))
    git(branch, "update-ref", "refs/pull/1/head", head)
    git(branch, "switch", "--quiet", "main")
    git(branch, "branch", "--quiet", "--delete", "--force", "feat/x")
    # What GitHub allows: fetching any reachable commit by its SHA, with a filter.
    git(branch, "config", "uploadpack.allowFilter", "true")
    git(branch, "config", "uploadpack.allowAnySHA1InWant", "true")
    return branch, base, head


def test_fetch_from_checks_commits_the_checkout_lacks(remote: tuple[Path, str, str], tmp_path: Path) -> None:
    repo, base, head = remote
    empty = tmp_path / "workspace"
    empty.mkdir()
    result = check(empty, "--fetch-from", repo.as_uri(), base=base, head=head)
    assert result.returncode == 1, result.stderr
    assert '"Second"' in result.stdout
    assert '"First"' not in result.stdout
    assert "author is Someone Else" in result.stdout


# The action's own step, run with bash as GitHub runs it, with its default inputs.


def run_action(env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    action = yaml.safe_load((ACTION / "action.yml").read_text())
    step = action["runs"]["steps"][0]
    inputs = {name: spec["default"] for name, spec in action["inputs"].items()}
    step_env = {
        "EVENT_NAME": "pull_request",
        "PR_AUTHOR": "Abrunacci",
        "NAME": inputs["name"],
        "EMAILS": inputs["emails"],
        "BLOCKED_DOMAINS": inputs["blocked-domains"],
        "ALLOW_DEPENDABOT": inputs["allow-dependabot"],
        "ALLOW_RENOVATE": inputs["allow-renovate"],
        "FETCH_TOKEN": "",
        "GITHUB_ACTION_PATH": str(ACTION),
        **env,
    }
    return subprocess.run(
        ["bash", "--noprofile", "--norc", "-eo", "pipefail", "-c", step["run"]],
        env=isolated_env(step_env),
        capture_output=True,
        text=True,
        check=False,
    )


def test_action_skips_events_without_a_pull_request() -> None:
    result = run_action({"EVENT_NAME": "push", "PR_BASE": "", "PR_HEAD": "", "REPO_URL": "x"})
    assert result.returncode == 0, result.stderr
    assert "Nothing to check: 'push'" in result.stdout


def test_action_checks_with_its_defaults(remote: tuple[Path, str, str]) -> None:
    repo, base, head = remote
    env = {"PR_BASE": base, "PR_HEAD": head, "REPO_URL": repo.as_uri()}
    result = run_action(env)
    # The defaults name the real maintainer, so the test's Jane Doe is rejected, on both commits.
    assert result.returncode == 1, result.stderr
    assert '"First"' in result.stdout
    assert '"Second"' in result.stdout
    assert "expected Alejandro Brunacci <abrunacci87@gmail.com> or Alejandro" in result.stdout


def test_action_passes_the_maintainer_and_dependabot(branch: Path) -> None:
    base = git(branch, "rev-parse", "main")
    maintainer = ("Alejandro Brunacci", "abrunacci87@gmail.com")
    dependabot_commit(branch)
    head = commit(branch, "Adapt", author=maintainer)
    git(branch, "config", "uploadpack.allowFilter", "true")
    env = {"PR_BASE": base, "PR_HEAD": head, "REPO_URL": branch.as_uri()}
    result = run_action({**env, "PR_AUTHOR": "dependabot[bot]"})
    assert result.returncode == 0, result.stdout + result.stderr
    assert "2 commit(s) checked" in result.stdout
    # The same commits in a pull request someone else opened.
    assert run_action(env).returncode == 1


def test_action_passes_renovate(branch: Path) -> None:
    base = git(branch, "rev-parse", "main")
    head = commit(branch, "chore(deps): update caddy", author=RENOVATE, committer=GITHUB)
    git(branch, "config", "uploadpack.allowFilter", "true")
    env = {"PR_BASE": base, "PR_HEAD": head, "REPO_URL": branch.as_uri()}
    result = run_action({**env, "PR_AUTHOR": "renovate[bot]"})
    assert result.returncode == 0, result.stdout + result.stderr
    assert run_action(env).returncode == 1
