"""Check that every commit of a pull request is the maintainer's and carries no attribution.

Every commit in ``BASE..HEAD`` must be authored by the maintainer (one name, any of the given
emails) and committed by the maintainer or by GitHub, which is the committer of "Update branch"
merges and of edits made in the web editor. No commit message may carry a ``Co-Authored-By``
trailer, a line starting with "Generated with/by", a line starting with "Requested by ...
thread", or a link to a blocked domain.

With ``--allow-dependabot``, a pull request that Dependabot opened may also carry Dependabot's
commits. Who opened the pull request comes from GitHub, not from the commits, so in any other
pull request a commit that claims to be Dependabot's is rejected. Their messages are still
checked.

Standard library only, so the action runs it with the runner's Python and no install step::

    python3 check_authorship.py --base BASE_SHA --head HEAD_SHA \\
        --name "Jane Doe" --email jane@example.com \\
        --blocked-domain example.org \\
        --fetch-from https://github.com/owner/repo

With ``--fetch-from``, the commits are fetched into a throwaway repository first (commits only,
no files), so the caller's checkout can be shallow or missing. Without it, the repository in
the current directory must already hold both commits and the history between them.

Exits 0 when every commit passes, 1 with a report of every problem and how to fix it, and 2 when
git cannot read the commits.
"""

from __future__ import annotations

import argparse
import base64
import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass

# The lines are matched at the start of a line, after any markup (``_``, ``*``, ``>``, an
# emoji), so prose that merely mentions "generated by" mid-sentence still passes.
LEAD = r"^[^A-Za-z0-9]*"
LINE_RULES: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("a Co-Authored-By trailer", re.compile(LEAD + r"co-authored-by\s*:", re.IGNORECASE)),
    ("a 'Generated with/by' line", re.compile(LEAD + r"generated\s+(with|by)\b", re.IGNORECASE)),
    (
        "a 'Requested by ... thread' line",
        re.compile(LEAD + r"requested\s+by\b.*\bthread\b", re.IGNORECASE),
    ),
)

# GitHub commits "Update branch" merges and web edits with this identity, on the author's behalf.
GITHUB = ("GitHub", "noreply@github.com")
# The login that opens Dependabot's pull requests, and the identity its commits carry.
DEPENDABOT_LOGIN = "dependabot[bot]"
DEPENDABOT = ("dependabot[bot]", "49699333+dependabot[bot]@users.noreply.github.com")

# Fields of `git log` are separated by NUL and records by RS, which cannot appear in a message.
FIELDS = ("sha", "author_name", "author_email", "committer_name", "committer_email", "message")
LOG_FORMAT = "%H%x00%an%x00%ae%x00%cn%x00%ce%x00%B%x1e"


@dataclass(frozen=True)
class Commit:
    sha: str
    author_name: str
    author_email: str
    committer_name: str
    committer_email: str
    message: str

    @property
    def label(self) -> str:
        subject = self.message.splitlines()[0] if self.message else ""
        return f'commit {self.sha[:12]} "{subject}"'


@dataclass(frozen=True)
class Policy:
    """Who may author and commit, and which domains no message may link to."""

    name: str
    emails: tuple[str, ...]
    domains: tuple[str, ...]
    dependabot: bool = False

    def is_maintainer(self, name: str, email: str) -> bool:
        return name == self.name and email.lower() in (e.lower() for e in self.emails)

    def may_author(self, name: str, email: str) -> bool:
        return self.is_maintainer(name, email) or (self.dependabot and same(name, email, DEPENDABOT))

    def may_commit(self, name: str, email: str) -> bool:
        return self.may_author(name, email) or same(name, email, GITHUB)

    @property
    def expected(self) -> str:
        return " or ".join(f"{self.name} <{email}>" for email in self.emails)


def same(name: str, email: str, identity: tuple[str, str]) -> bool:
    return name == identity[0] and email.lower() == identity[1].lower()


def domain_rule(domain: str) -> re.Pattern[str]:
    """Matches the domain and its subdomains, but not a longer name that ends the same way."""
    return re.compile(rf"(?<![\w-])(?:[\w-]+\.)*{re.escape(domain)}(?![\w-])", re.IGNORECASE)


def line_problems(text: str, domains: Sequence[str]) -> Iterator[tuple[int, str, str]]:
    """Yields ``(line number, what is wrong, the line)`` for every forbidden line in ``text``."""
    rules = [*LINE_RULES, *((f"a link to {domain}", domain_rule(domain)) for domain in domains)]
    for number, line in enumerate(text.splitlines(), start=1):
        for what, rule in rules:
            if rule.search(line):
                yield number, what, line.strip()


def git(*args: str, env: Mapping[str, str] | None = None) -> str:
    return subprocess.run(
        ["git", *args],
        check=True,
        capture_output=True,
        text=True,
        env={**os.environ, **(env or {})},
    ).stdout


def fetch(url: str, base: str, head: str, token: str) -> dict[str, str]:
    """Fetches the commits of ``base`` and ``head`` into a throwaway bare repository.

    Only commits travel (``tree:0``): the check reads authors and messages, never files, so
    the download stays small however big the repository is. Returns the environment that points
    git at that repository.
    """
    git_dir = tempfile.mkdtemp(prefix="check-commit-metadata-")
    repo = {"GIT_DIR": git_dir, "GIT_NO_LAZY_FETCH": "1"}
    git("init", "--quiet", "--bare", git_dir)
    git("remote", "add", "origin", url, env=repo)
    git("config", "remote.origin.promisor", "true", env=repo)
    git("config", "remote.origin.partialclonefilter", "tree:0", env=repo)
    auth = {}
    if token:
        # Through the environment, never the command line, so no process listing shows it.
        basic = base64.b64encode(f"x-access-token:{token}".encode()).decode()
        auth = {
            "GIT_CONFIG_COUNT": "1",
            "GIT_CONFIG_KEY_0": "http.extraHeader",
            "GIT_CONFIG_VALUE_0": f"AUTHORIZATION: basic {basic}",
        }
    git("fetch", "--quiet", "--no-tags", "--filter=tree:0", "origin", base, head, env=repo | auth)
    return repo


def read_commits(base: str, head: str, env: Mapping[str, str] | None = None) -> list[Commit]:
    out = git("log", f"--format={LOG_FORMAT}", f"{base}..{head}", env=env)
    records = [record.strip("\n") for record in out.split("\x1e")]
    return [Commit(**dict(zip(FIELDS, r.split("\x00"), strict=True))) for r in records if r]


def check_commit(commit: Commit, policy: Policy) -> list[str]:
    problems: list[str] = []
    if not policy.may_author(commit.author_name, commit.author_email):
        problems.append(f"author is {commit.author_name} <{commit.author_email}>, expected {policy.expected}")
    if not policy.may_commit(commit.committer_name, commit.committer_email):
        problems.append(
            f"committer is {commit.committer_name} <{commit.committer_email}>, "
            f"expected the author or {GITHUB[0]} <{GITHUB[1]}>"
        )
    for number, what, line in line_problems(commit.message, policy.domains):
        problems.append(f"message line {number} is {what}: {line}")
    return problems


COMMIT_FIX = """\
How to fix the commits:
  - Wrong author or committer: set your identity and rewrite the branch's commits with it:
      git config user.name "{name}" && git config user.email "{email}"
      git rebase --exec 'git commit --amend --no-edit --reset-author' {base}
  - A forbidden line: run `git rebase -i {base}`, mark the commit `reword` and delete the line.
  Then push with `git push --force-with-lease`."""


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--base", required=True, help="the pull request's base commit")
    parser.add_argument("--head", required=True, help="the pull request's head commit")
    parser.add_argument("--name", required=True, help="the only accepted author name")
    parser.add_argument("--email", action="append", required=True, help="an accepted author email (repeatable)")
    parser.add_argument(
        "--blocked-domain",
        action="append",
        default=[],
        help="a domain no message may link to, subdomains included (repeatable)",
    )
    parser.add_argument(
        "--allow-dependabot",
        action="store_true",
        help="accept Dependabot's commits when Dependabot opened the pull request",
    )
    parser.add_argument("--pr-author", default="", help="the login that opened the pull request")
    parser.add_argument("--fetch-from", metavar="URL", help="fetch the commits from this repository first")
    args = parser.parse_args(argv)

    policy = Policy(
        name=args.name,
        emails=tuple(args.email),
        domains=tuple(args.blocked_domain),
        dependabot=args.allow_dependabot and args.pr_author == DEPENDABOT_LOGIN,
    )
    # The token is read from the environment so it never shows up in a command line.
    env = None
    if args.fetch_from:
        env = fetch(args.fetch_from, args.base, args.head, os.environ.get("FETCH_TOKEN", ""))

    report: list[str] = []
    commits = read_commits(args.base, args.head, env)
    bad_commits = 0
    for commit in commits:
        problems = check_commit(commit, policy)
        if problems:
            bad_commits += 1
            report.append(f"{commit.label}:")
            report.extend(f"  - {problem}" for problem in problems)

    if not report:
        print(f"Commit metadata OK: {len(commits)} commit(s) checked.")
        return 0
    report.append(COMMIT_FIX.format(name=args.name, email=args.email[0], base=args.base))
    if os.environ.get("GITHUB_ACTIONS") == "true":
        print(
            f"::error title=Check commit metadata::{bad_commits} of {len(commits)} commit(s) "
            "break the rules; see the log for details."
        )
    print("\n".join(report))
    return 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except subprocess.CalledProcessError as error:
        # A fetch or log that failed: show git's own words, not a traceback.
        print(f"`{' '.join(error.cmd)}` failed:\n{error.stderr.strip()}", file=sys.stderr)
        sys.exit(2)
